/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Client;
import Controller.C_Workers;
import Model.Role_User;
import Model.User;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Workers extends javax.swing.JInternalFrame {
    C_Workers cw = new C_Workers();
    int cod;
    private int fila = -1;
    private int sw = 0;
    DefaultTableModel tabla = new DefaultTableModel();
    
    public void ListarTBL(String dato){
        tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Usuario");
        tabla.addColumn("Nombre");
        tabla.addColumn("Rol");
        List<User> lista = cw.ListaTrabajadores(dato);
        tabla.setNumRows(lista.size());
        c1.setText("Registros: "+lista.size());
        c2.setText("Registros: "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_user(), i, 0);
            tabla.setValueAt(lista.get(i).getName_user(), i, 1);                      
            tabla.setValueAt(lista.get(i).getName_pers(), i, 2);                      
            tabla.setValueAt(lista.get(i).getDesc_role(), i, 3);                                          
        }
        Tabla.setModel(tabla);
        Tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void CB_Role(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Role_User> lista=cw.CB_Rol();
        for(Role_User r:lista){
            r = new Role_User(r.getCod_role(), r.getDesc_role());
            combo.addElement(r);
        }
        RolU.setModel(combo);
    }
    
    public FRM_Workers() {
        initComponents();
        CB_Role();
        ListarTBL("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        c1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        Agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        c2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        NomU = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        ApU = new javax.swing.JTextField();
        PassU = new javax.swing.JPasswordField();
        AmU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RolU = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setText("Cantidad:");
        jToolBar1.add(c1);

        jPanel3.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jToolBar2.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Agregar.setFocusable(false);
        Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jToolBar2.add(Agregar);
        jToolBar2.add(jSeparator1);

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/modificar.png"))); // NOI18N
        Modificar.setFocusable(false);
        Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jToolBar2.add(Modificar);

        jLabel2.setText("                                                                                              ");
        jToolBar2.add(jLabel2);
        jToolBar2.add(jSeparator2);

        Buscador.setBackground(new java.awt.Color(30, 136, 229));
        Buscador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buscador.setForeground(new java.awt.Color(0, 0, 0));
        Buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        jToolBar2.add(Buscador);
        jToolBar2.add(jSeparator5);

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jToolBar2.add(Eliminar);

        jPanel3.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        Tabla.setBackground(new java.awt.Color(206, 206, 206));
        Tabla.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 0, 0));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(51, 51, 51));
        Tabla.setRowHeight(25);
        Tabla.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.addTab("Trabajadores", jPanel3);

        jPanel4.setBackground(new java.awt.Color(176, 190, 197));

        jToolBar3.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setText("Cantidad:");
        jToolBar3.add(c2);
        jToolBar3.add(jSeparator6);

        jLabel1.setText("                                                                                                                                                                                                                    ");
        jToolBar3.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre de Usuario:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contraseña:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Apellido Paterno:");

        Guardar.setBackground(new java.awt.Color(128, 142, 149));
        Guardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setText("GUARDAR");
        Guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jToolBar5.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        NomU.setBackground(new java.awt.Color(30, 136, 229));
        NomU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NomU.setForeground(new java.awt.Color(0, 0, 0));
        NomU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NomU.setMinimumSize(new java.awt.Dimension(4, 23));

        Nom.setBackground(new java.awt.Color(30, 136, 229));
        Nom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 0, 0));
        Nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nom.setMinimumSize(new java.awt.Dimension(4, 23));

        ApU.setBackground(new java.awt.Color(30, 136, 229));
        ApU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ApU.setForeground(new java.awt.Color(0, 0, 0));
        ApU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ApU.setMinimumSize(new java.awt.Dimension(4, 23));

        PassU.setBackground(new java.awt.Color(30, 136, 229));
        PassU.setForeground(new java.awt.Color(0, 0, 0));
        PassU.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AmU.setBackground(new java.awt.Color(30, 136, 229));
        AmU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AmU.setForeground(new java.awt.Color(0, 0, 0));
        AmU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AmU.setMinimumSize(new java.awt.Dimension(4, 23));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apellido Materno:");

        RolU.setBackground(new java.awt.Color(30, 136, 229));
        RolU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RolU.setForeground(new java.awt.Color(0, 0, 0));
        RolU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rol:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(ApU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(PassU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RolU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AmU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(258, 258, 258))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NomU, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(NomU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(PassU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(ApU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addComponent(AmU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addComponent(RolU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        Panel.addTab("Gestion", jPanel4);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        sw = 0;
        Panel.setSelectedIndex(1);
        NomU.grabFocus();
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if (fila>-1) {
            cod=Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0)));
            sw=1;
            Panel.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        ListarTBL(Buscador.getText());
    }//GEN-LAST:event_BuscadorKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if(fila>-1){
            int res = JOptionPane.showConfirmDialog(this, "Realmente desea eliminar el registro?");
            if (res == 0) {
                cw.EliminarTrabajadores(Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0))));
                ListarTBL("");
                JOptionPane.showMessageDialog(this, "Registro eliminado", "Advertencia", JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
                fila = -1;
            }
        }else{
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","Advertencia",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        fila=Tabla.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaMouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Role_User r = (Role_User)RolU.getSelectedItem();
        String pass=String.copyValueOf(PassU.getPassword());
        if (NomU.getText().equals("") || pass.equals("") || AmU.getText().equals("") || ApU.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (sw==0) cw.AgregarTrabajadores(NomU.getText(), pass, Nom.getText(), ApU.getText(), AmU.getText(), r.getCod_role());
            else cw.EditarTrabajadores(cod, NomU.getText(), Nom.getText(), ApU.getText(), AmU.getText(), r.getCod_role());
            JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);

        }
        NomU.setText("");
        Nom.setText("");
        Nom.setText("");
        ApU.setText("");
        sw=0;
        ListarTBL("");
        Panel.setSelectedIndex(0);
    }//GEN-LAST:event_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField AmU;
    private javax.swing.JTextField ApU;
    private javax.swing.JTextField Buscador;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField NomU;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JPasswordField PassU;
    private javax.swing.JComboBox<String> RolU;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar5;
    // End of variables declaration//GEN-END:variables
}
