/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Membership;
import Model.Client;
import Model.Model_Payment;
import Model.Plan;
import Model.Type_plan;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mark-
 */
public class FRM_Membership extends javax.swing.JInternalFrame {
    C_Membership cm = new C_Membership();
    int cod;
    private int fila = -1;
    private int sw = 0;
    DefaultTableModel tabla = new DefaultTableModel();
    
    public void ListarTBL(String dato){
        tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Trabajador");
        tabla.addColumn("Cliente");
        tabla.addColumn("Pago");
        tabla.addColumn("Membresia");
        tabla.addColumn("Ingreso");
        tabla.addColumn("Fecha Fin");
        List<Plan> lista = cm.ListMembership(dato);
        tabla.setNumRows(lista.size());
        c1.setText("Registros: "+lista.size());
        c2.setText("Registros: "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_plan(), i, 0);
            tabla.setValueAt(lista.get(i).getName_pers(), i, 1);
            tabla.setValueAt(lista.get(i).getName_client(), i, 2);
            tabla.setValueAt(lista.get(i).getDesc_model(), i, 3);
            tabla.setValueAt(lista.get(i).getDesc_type(), i, 4);
            tabla.setValueAt(lista.get(i).getDate_in(), i, 5);            
            tabla.setValueAt(lista.get(i).getDate_end(), i, 6);            

        }
        Tabla.setModel(tabla);
        Tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void CB_TipoMembresia(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Type_plan> lista=cm.C_TipoMembresia();
        for(Type_plan tp:lista){
            tp = new Type_plan(tp.getCod_type(), tp.getDesc_type());
            combo.addElement(tp);
        }
        Membresia.setModel(combo);
    }
    
    private void CB_MetodoPago(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Model_Payment> lista=cm.C_MetodoPago();
        for(Model_Payment mp:lista){
            mp = new Model_Payment(mp.getCod_model(), mp.getDesc_model());
            combo.addElement(mp);
        }
        MetodoPago.setModel(combo);
    }
    
    private void CB_Client(){
       DefaultComboBoxModel combo = new DefaultComboBoxModel();
        List<Client> lista=cm.C_Cliente();
        for(Client c:lista){
            c = new Client(c.getCod_client(), c.getRut_client());
            combo.addElement(c);
        }
        Cliente.setModel(combo);
    }
    
    
    public FRM_Membership() {
        initComponents();
        ListarTBL("");
        CB_TipoMembresia();
        CB_MetodoPago();
        CB_Client();
        usu.setVisible(false);
        usu.setText(Login.NomU.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        c1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        refreshList = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        Agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        c2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FechaIngreso = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Membresia = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        MetodoPago = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Cliente = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        usu = new javax.swing.JLabel();
        FormCliente = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(176, 190, 197));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setText("Cantidad:");
        jToolBar1.add(c1);
        jToolBar1.add(jSeparator3);

        refreshList.setBackground(new java.awt.Color(178, 215, 255));
        refreshList.setForeground(new java.awt.Color(178, 215, 255));
        refreshList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/recargarlista.png"))); // NOI18N
        refreshList.setFocusable(false);
        refreshList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshList.setPreferredSize(new java.awt.Dimension(18, 18));
        refreshList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshListActionPerformed(evt);
            }
        });
        jToolBar1.add(refreshList);

        jPanel2.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jToolBar2.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Agregar.setFocusable(false);
        Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jToolBar2.add(Agregar);
        jToolBar2.add(jSeparator1);

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/modificar.png"))); // NOI18N
        Modificar.setFocusable(false);
        Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jToolBar2.add(Modificar);

        jLabel2.setText("                                                                                              ");
        jToolBar2.add(jLabel2);
        jToolBar2.add(jSeparator2);

        Buscador.setBackground(new java.awt.Color(30, 136, 229));
        Buscador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buscador.setForeground(new java.awt.Color(0, 0, 0));
        Buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        jToolBar2.add(Buscador);
        jToolBar2.add(jSeparator5);

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jToolBar2.add(Eliminar);

        jPanel2.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        Tabla.setBackground(new java.awt.Color(206, 206, 206));
        Tabla.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 0, 0));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(51, 51, 51));
        Tabla.setRowHeight(25);
        Tabla.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.addTab("Lista de Cupos", jPanel2);

        jPanel1.setBackground(new java.awt.Color(176, 190, 197));

        jToolBar3.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setText("Cantidad:");
        jToolBar3.add(c2);
        jToolBar3.add(jSeparator6);

        jLabel1.setText("                                                                                                                                                                                                                    ");
        jToolBar3.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha de Ingreso:");

        FechaIngreso.setBackground(new java.awt.Color(30, 136, 229));
        FechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        try {
            FechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FechaIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FechaIngreso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("(AAAA-MM-DD)");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Membresia:");

        Membresia.setBackground(new java.awt.Color(30, 136, 229));
        Membresia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Membresia.setForeground(new java.awt.Color(0, 0, 0));
        Membresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Metodo de Pago:");

        MetodoPago.setBackground(new java.awt.Color(30, 136, 229));
        MetodoPago.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MetodoPago.setForeground(new java.awt.Color(0, 0, 0));
        MetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cliente:");

        Cliente.setBackground(new java.awt.Color(30, 136, 229));
        Cliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Guardar.setBackground(new java.awt.Color(128, 142, 149));
        Guardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setText("GUARDAR");
        Guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jToolBar5.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        usu.setBackground(new java.awt.Color(0, 0, 0));
        usu.setForeground(new java.awt.Color(176, 190, 197));
        usu.setText("jLabel3");

        FormCliente.setBackground(new java.awt.Color(176, 190, 197));
        FormCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_client.png"))); // NOI18N
        FormCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormClienteActionPerformed(evt);
            }
        });

        Actualizar.setBackground(new java.awt.Color(176, 190, 197));
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reload.png"))); // NOI18N
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usu)
                .addGap(163, 163, 163))
            .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(MetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FormCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Panel.addTab("Gestion", jPanel1);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        ListarTBL(Buscador.getText());
    }//GEN-LAST:event_BuscadorKeyTyped

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        sw = 0;
        Panel.setSelectedIndex(1);
        FechaIngreso.grabFocus();
        CB_Client();
        Cliente.setEnabled(true);
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if(fila>-1){
            int res = JOptionPane.showConfirmDialog(this, "Realmente desea eliminar el registro?");
            if (res == 0) {
                cm.EliminarM(Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0))));
                ListarTBL("");
                JOptionPane.showMessageDialog(this, "Registro eliminado", "Advertencia", JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
        JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","Advertencia",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        fila=Tabla.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaMouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Type_plan t = (Type_plan)Membresia.getSelectedItem();
        Model_Payment m = (Model_Payment)MetodoPago.getSelectedItem();
        Client c = (Client)Cliente.getSelectedItem();
        if (FechaIngreso.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar la fecha de ingreso", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (sw==0) cm.AgregarM(usu.getText(), c.getCod_client(), m.getCod_model(), t.getCod_type(), Date.valueOf(FechaIngreso.getText()));
            else cm.ModificarM(cod, m.getCod_model(), t.getCod_type(), Date.valueOf(FechaIngreso.getText()));
        }
        FechaIngreso.setText("");
        sw=0;
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        ListarTBL("");
        Panel.setSelectedIndex(0);
    }//GEN-LAST:event_GuardarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if (fila>-1) {
            cod=Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0)));
            sw=1;
            Panel.setSelectedIndex(1);
            Cliente.setEnabled(false);
        } else {
           JOptionPane.showMessageDialog(this, "Debe seleccionar una fila","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        CB_Client();
    }//GEN-LAST:event_ActualizarActionPerformed

    private void FormClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormClienteActionPerformed
        FRM_Client2 frmc = new FRM_Client2();
        Principal.PanelDesktop.add(frmc);
        Principal.centrar(frmc);
    }//GEN-LAST:event_FormClienteActionPerformed

    private void refreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshListActionPerformed
        ListarTBL("");
    }//GEN-LAST:event_refreshListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Buscador;
    private javax.swing.JComboBox<String> Cliente;
    private javax.swing.JButton Eliminar;
    private javax.swing.JFormattedTextField FechaIngreso;
    private javax.swing.JButton FormCliente;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> Membresia;
    private javax.swing.JComboBox<String> MetodoPago;
    private javax.swing.JButton Modificar;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JButton refreshList;
    public static javax.swing.JLabel usu;
    // End of variables declaration//GEN-END:variables
}
