/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Client;
import Model.Client;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mark-
 */
public class FRM_Client extends javax.swing.JInternalFrame {
    C_Client cc = new C_Client();
    int cod;
    private int fila = -1;
    private int sw = 0;
    DefaultTableModel tabla = new DefaultTableModel();
    
    public void ListarTBL(String dato){
        tabla.setColumnCount(0);
        tabla.addColumn("Codigo");
        tabla.addColumn("Rut");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido Paterno");
        tabla.addColumn("Apellido Materno");
        List<Client> lista = cc.ListaClientes(dato);
        tabla.setNumRows(lista.size());
        c1.setText("Registros: "+lista.size());
        c2.setText("Registros: "+lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getCod_client(), i, 0);
            tabla.setValueAt(lista.get(i).getRut_client(), i, 1);                      
            tabla.setValueAt(lista.get(i).getName_client(), i, 2);                      
            tabla.setValueAt(lista.get(i).getApp_client(), i, 3);                      
            tabla.setValueAt(lista.get(i).getApm_client(), i, 4);                      
        }
        Tabla.setModel(tabla);
        Tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        Tabla.getColumnModel().getColumn(0).setMinWidth(0);
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    /**
     * Creates new form FRM_Client
     */
    public FRM_Client() {
        initComponents();
        ListarTBL("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Panel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        c1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        refreshList = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        Agregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Modificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        Buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        c2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        Rut = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        Ap = new javax.swing.JTextField();
        Am = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(176, 190, 197));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel2.setBackground(new java.awt.Color(176, 190, 197));
        jPanel2.setLayout(new java.awt.BorderLayout());

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setText("Cantidad:");
        jToolBar1.add(c1);
        jToolBar1.add(jSeparator3);

        refreshList.setBackground(new java.awt.Color(178, 215, 255));
        refreshList.setForeground(new java.awt.Color(178, 215, 255));
        refreshList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/recargarlista.png"))); // NOI18N
        refreshList.setFocusable(false);
        refreshList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshList.setPreferredSize(new java.awt.Dimension(18, 18));
        refreshList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshListActionPerformed(evt);
            }
        });
        jToolBar1.add(refreshList);

        jPanel3.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jToolBar2.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Agregar.setFocusable(false);
        Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jToolBar2.add(Agregar);
        jToolBar2.add(jSeparator1);

        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/modificar.png"))); // NOI18N
        Modificar.setFocusable(false);
        Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jToolBar2.add(Modificar);

        jLabel2.setText("                                                                                              ");
        jToolBar2.add(jLabel2);
        jToolBar2.add(jSeparator2);

        Buscador.setBackground(new java.awt.Color(30, 136, 229));
        Buscador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Buscador.setForeground(new java.awt.Color(0, 0, 0));
        Buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscadorKeyTyped(evt);
            }
        });
        jToolBar2.add(Buscador);
        jToolBar2.add(jSeparator5);

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        Eliminar.setFocusable(false);
        Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jToolBar2.add(Eliminar);

        jPanel3.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        Tabla.setBackground(new java.awt.Color(206, 206, 206));
        Tabla.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 0, 0));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setGridColor(new java.awt.Color(51, 51, 51));
        Tabla.setRowHeight(25);
        Tabla.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Panel.addTab("Lista de Clientes", jPanel3);

        jPanel4.setBackground(new java.awt.Color(176, 190, 197));

        jToolBar3.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setText("Cantidad:");
        jToolBar3.add(c2);
        jToolBar3.add(jSeparator6);

        jLabel1.setText("                                                                                                                                                                                                                    ");
        jToolBar3.add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RUT:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Apellido Paterno:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Apellido Materno:");

        Guardar.setBackground(new java.awt.Color(128, 142, 149));
        Guardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(0, 0, 0));
        Guardar.setText("GUARDAR");
        Guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jToolBar5.setBackground(new java.awt.Color(178, 215, 255));
        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);

        Rut.setBackground(new java.awt.Color(30, 136, 229));
        Rut.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Rut.setForeground(new java.awt.Color(0, 0, 0));
        Rut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Rut.setMinimumSize(new java.awt.Dimension(4, 23));

        Nom.setBackground(new java.awt.Color(30, 136, 229));
        Nom.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nom.setForeground(new java.awt.Color(0, 0, 0));
        Nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nom.setMinimumSize(new java.awt.Dimension(4, 23));

        Ap.setBackground(new java.awt.Color(30, 136, 229));
        Ap.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Ap.setForeground(new java.awt.Color(0, 0, 0));
        Ap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ap.setMinimumSize(new java.awt.Dimension(4, 23));

        Am.setBackground(new java.awt.Color(30, 136, 229));
        Am.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Am.setForeground(new java.awt.Color(0, 0, 0));
        Am.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Am.setMinimumSize(new java.awt.Dimension(4, 23));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(261, 261, 261))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(Am, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(Ap, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(Rut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(Ap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(Am, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        Rut.getAccessibleContext().setAccessibleName("");

        Panel.addTab("Gestion", jPanel4);

        jPanel2.add(Panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        sw = 0;
        Panel.setSelectedIndex(1);
        Rut.grabFocus();
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if (fila>-1) {
            cod=Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0)));
            Rut.setText(String.valueOf(Tabla.getValueAt(fila, 1)));
            Nom.setText(String.valueOf(Tabla.getValueAt(fila, 2)));
            Ap.setText(String.valueOf(Tabla.getValueAt(fila, 3)));
            Am.setText(String.valueOf(Tabla.getValueAt(fila, 4)));
            sw=1;
            Panel.setSelectedIndex(1);
        } else {
           JOptionPane.showMessageDialog(this, "Debe seleccionar una fila","ADVERTENCIA",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void BuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscadorKeyTyped
        ListarTBL(Buscador.getText());
    }//GEN-LAST:event_BuscadorKeyTyped

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if(fila>-1){
            int res = JOptionPane.showConfirmDialog(this, "Realmente desea eliminar el registro?");
            if (res == 0) {
                cc.EliminarC(Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0))));
                ListarTBL("");
                JOptionPane.showMessageDialog(this, "Registro eliminado", "Advertencia", JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
        JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA FILA","Advertencia",JOptionPane.OK_OPTION+JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        fila=Tabla.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TablaMouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (Rut.getText().equals("") || Nom.getText().equals("") || Ap.getText().equals("") || Am.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (sw==0) cc.AgregarC(Rut.getText(), Nom.getText(), Ap.getText(), Am.getText());
            else cc.ModificarC(cod, Rut.getText(), Nom.getText(), Ap.getText(), Am.getText());
        }
        Rut.setText("");
        Nom.setText("");
        Ap.setText("");
        Am.setText("");
        sw=0;
        JOptionPane.showMessageDialog(this, "OPERACION REALIZADA", "EvolutionGym",JOptionPane.OK_OPTION+JOptionPane.INFORMATION_MESSAGE);
        ListarTBL("");
        Panel.setSelectedIndex(0);
    }//GEN-LAST:event_GuardarActionPerformed

    private void refreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshListActionPerformed
        ListarTBL("");
    }//GEN-LAST:event_refreshListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Am;
    private javax.swing.JTextField Ap;
    private javax.swing.JTextField Buscador;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nom;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JTextField Rut;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JButton refreshList;
    // End of variables declaration//GEN-END:variables
}
