/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Conecction;
import Controller.C_User;
import Model.User;
import java.util.ArrayList;

/**
 *
 * @author Mark-
 */
public class Login extends javax.swing.JInternalFrame {
    ArrayList<User> lista;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.lista=lista;
        Alerta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomU = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_IniciarSesion = new javax.swing.JButton();
        Alerta = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel1.setBackground(new java.awt.Color(176, 190, 197));

        NomU.setBackground(new java.awt.Color(30, 136, 229));
        NomU.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NomU.setForeground(new java.awt.Color(0, 0, 0));
        NomU.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Pass.setBackground(new java.awt.Color(30, 136, 229));
        Pass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Pass.setForeground(new java.awt.Color(0, 0, 0));
        Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass.setPreferredSize(new java.awt.Dimension(14, 32));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contraseña:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de Usuario:");

        btn_IniciarSesion.setBackground(new java.awt.Color(128, 142, 149));
        btn_IniciarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_IniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btn_IniciarSesion.setText("Iniciar Sesion");
        btn_IniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarSesionActionPerformed(evt);
            }
        });

        Alerta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Alerta.setForeground(new java.awt.Color(155, 0, 0));
        Alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Alerta.setText("Usuario o Contraseña incorrectos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomU)
                    .addComponent(btn_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Alerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Alerta)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarSesionActionPerformed
        C_User control=new C_User();
        String pass=String.copyValueOf(Pass.getPassword());
        if (control.Login(NomU.getText(), pass, "Administrador")) {
            Principal.N_user.setText("BIENVENIDO: "+NomU.getText());
            Principal.btnMembresia.setVisible(true);
            Principal.btnClientes.setVisible(true);
            Principal.btnInventario.setVisible(true);
            Principal.btnTrabajadores.setVisible(true);

            this.dispose();
        }else if(control.Login(NomU.getText(), pass, "Entrenador")){
            Principal.N_user.setText("BIENVENIDO: "+NomU.getText());
            Principal.btnMembresia.setVisible(true);
            Principal.btnInventario.setVisible(true);
            this.dispose();
        }else{
            NomU.setText("");
            Pass.setText("");
            Alerta.setVisible(true);
            Alerta.setText("USUARIO O PASSWORD INCORRECTO");
        }
    }//GEN-LAST:event_btn_IniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    public static javax.swing.JTextField NomU;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JButton btn_IniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
